package com.example.valutes

data class ExistingValutes(
    val AUD: ValuteEntity,
    val AZN: ValuteEntity,
    val GBP: ValuteEntity,
    val AMD: ValuteEntity,
    val BYN: ValuteEntity,
    val BGN: ValuteEntity,
    val BRL: ValuteEntity,
    val HUF: ValuteEntity,
    val HKD: ValuteEntity,
    val DKK: ValuteEntity,
    val USD: ValuteEntity,
    val EUR: ValuteEntity,
    val INR: ValuteEntity,
    val KZT: ValuteEntity,
    val CAD: ValuteEntity,
    val KGS: ValuteEntity,
    val CNY: ValuteEntity,
    val MDL: ValuteEntity,
    val NOK: ValuteEntity,
    val PLN: ValuteEntity,
    val RON: ValuteEntity,
    val XDR: ValuteEntity,
    val SGD: ValuteEntity,
    val TJS: ValuteEntity,
    val TRY: ValuteEntity,
    val TMT: ValuteEntity,
    val UZS: ValuteEntity,
    val UAH: ValuteEntity,
    val CZK: ValuteEntity,
    val SEK: ValuteEntity,
    val CHF: ValuteEntity,
    val ZAR: ValuteEntity,
    val KRW: ValuteEntity,
    val JPY: ValuteEntity
) {
    fun getValutesList(): List<ValuteEntity> = listOf(
        AUD,
        AZN,
        GBP,
        AMD,
        BYN,
        BGN,
        BRL,
        HUF,
        HKD,
        DKK,
        USD,
        EUR,
        INR,
        KZT,
        CAD,
        KGS,
        CNY,
        MDL,
        NOK,
        PLN,
        RON,
        XDR,
        SGD,
        TJS,
        TRY,
        TMT,
        UZS,
        UAH,
        CZK,
        SEK,
        CHF,
        ZAR,
        KRW,
        JPY
    )
}